### ISSUE TITLE
Validate user dashboard stats returning as expected

### ISSUE THREAD

**Issue by AkinariHex** [osu-tournament-rating/otr-api#353] opened 2024-08-27 15:45 UTC
When asking data to both endpoints `/me/stats` and `/stats/{id}` returns null and empty values.

Tested in branch: `feature/data-processor-rewrite`

![image](https://github.com/user-attachments/assets/9ba25b91-3207-48fa-9594-ec81684f8aef)
![image](https://github.com/user-attachments/assets/1c8e315b-6eef-49c5-a4b4-7982ca7fab23)

**Comment by hburn7** [comment] 2024-08-29 16:51
I feel like this will be fixed once we get the new database populated

**Comment by hburn7** [comment] 2024-10-06 01:58
Duplicate of #72

**Closed by hburn7** 2024-10-06 01:58 UTC
Labels: bug
